<a href="https://colab.research.google.com/github/RealRohitDudi/Data_Science_Notes/blob/main/Copy_of_task_15_numpy_tricks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###`Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr =
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [2]:
# code here
# i. Sort this matrix. np.sort()
# ii. Sort this matrix based on values in 2nd column.
# iii. Sort this matrix based on max value in each row.
# iv. Sort based on elements value.
import numpy as np
arr = np.random.randint(1,100,12).reshape(3,4)
print(arr)
print("sorted: \n",np.sort(arr))
arr[:,1] = np.sort(arr[:,1],axis=-1)
print("2nd column sorted: \n", arr)

for row in arr:
    row.sort()
print("max value in each row: \n", arr)

flat_sort = np.sort(arr,axis=None)
print("based on elements value: \n", flat_sort)

[[23 78 30 72]
 [78  2 74 13]
 [46 27 61 54]]
sorted: 
 [[23 30 72 78]
 [ 2 13 74 78]
 [27 46 54 61]]
2nd column sorted: 
 [[23  2 30 72]
 [78 27 74 13]
 [46 78 61 54]]
max value in each row: 
 [[ 2 23 30 72]
 [13 27 74 78]
 [46 54 61 78]]
based on elements value: 
 [ 2 13 23 27 30 46 54 61 72 74 78 78]


###`Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [ ]:
# code here
# students  = row
marks = np.array([[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]])

extra_subject = np.array([41, 87, 72, 36, 92]).reshape(-1,1)
merged = np.hstack((marks,extra_subject))
print("marks after adding extra subject: \n", merged)
#do not touch til

student1 = np.array([31, 85, 75, 66, 52]).reshape(1,-1)
student2 = np.array([31, 27, 73, 46, 32]).reshape(1,-1)


updated_students = np.vstack((merged,student1,student2))
print("after adding 2 more students \n",updated_students)


total_marks = np.sum(updated_students,axis=1).reshape(-1,1)
sum_added = np.hstack((updated_students,total_marks))
print("after adding sum column",sum_added)


sum_added[:,5] = np.sort(sum_added[:,5])[::-1]
print("after sorting based on sum column descening()",sum_added)



marks after adding extra subject: 
 [[13 10  9 33 41]
 [63 46 90 42 87]
 [39 76 13 29 72]
 [82  9 29 78 36]
 [67 61 59 36 92]]
after adding 2 more students 
 [[13 10  9 33 41]
 [63 46 90 42 87]
 [39 76 13 29 72]
 [82  9 29 78 36]
 [67 61 59 36 92]
 [31 85 75 66 52]
 [31 27 73 46 32]]
after adding sum column [[ 13  10   9  33  41 106]
 [ 63  46  90  42  87 328]
 [ 39  76  13  29  72 229]
 [ 82   9  29  78  36 234]
 [ 67  61  59  36  92 315]
 [ 31  85  75  66  52 309]
 [ 31  27  73  46  32 209]]
after sorting based on sum column descening() [[ 13  10   9  33  41 328]
 [ 63  46  90  42  87 315]
 [ 39  76  13  29  72 309]
 [ 82   9  29  78  36 234]
 [ 67  61  59  36  92 229]
 [ 31  85  75  66  52 209]
 [ 31  27  73  46  32 106]]


###`Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [8]:
# code here
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])

row_unique = np.unique(arr,axis=0)
col_unique = np.unique(arr,axis=1)
print("row unique: \n", row_unique)
print("column unique: \n", col_unique)




row unique: 
 [[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]
column unique: 
 [[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]


###`Q-4:` Flip given 2-D array along both axes at the same time.

In [ ]:
# code here

### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [23]:
# code here
arr = np.array([[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]])

print("Original array: \n",arr)

print("Flipped array: \n",(np.flip(arr)))

Original array: 
 [[ 1  2  3  4  5]
 [10 -3 30  4  5]
 [ 3  2  5 -4  5]
 [ 9  7  3  6  5]]
Flipped array: 
 [[ 5  6  3  7  9]
 [ 5 -4  5  2  3]
 [ 5  4 30 -3 10]
 [ 5  4  3  2  1]]


### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [25]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

In [26]:
# code here
flattened = np.concatenate((arr1,arr2,arr3))
print(flattened)

[0 1 2 3 4 5 6 7 8 9]


### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [36]:
# code here
arr = np.random.randint(100, 1000, 200).reshape((1, 200))

print("original array: \n", arr)
print("maximum array \n", arr.min())
print("minimum array \n",arr.max())

min_index = np.argmin(arr)
max_index = np.argmax(arr)

arr = np.delete(arr,min_index)
arr = np.delete(arr,max_index)
print("after deleting min and max: \n", arr)

original array: 
 [[845 100 518 123 447 276 715 932 184 329 532 795 520 707 941 662 365 767
  697 931 577 654 920 501 247 588 236 469 768 785 836 848 122 310 463 654
  799 312 855 675 940 349 102 216 527 671 699 110 421 830 497 733 191 143
  273 516 893 319 429 846 196 479 793 524 924 569 703 753 418 800 409 947
  876 405 833 288 874 621 488 518 586 118 807 461 171 775 911 551 917 240
  598 638 969 865 148 805 718 602 462 775 457 239 325 929 492 790 403 806
  267 474 361 972 916 209 849 992 773 615 412 289 254 585 489 778 971 657
  667 559 693 344 505 183 290 349 969 295 297 500 736 208 290 141 229 726
  143 149 855 424 377 994 646 849 588 338 325 678 119 754 251 714 487 335
  285 175 322 882 917 778 124 370 196 721 676 882 331 828 577 879 409 711
  660 796 340 640 491 899 291 145 560 255 467 820 368 190 925 475 473 340
  558 846]]
maximum array 
 100
minimum array 
 994
after deleting min and max: 
 [845 518 123 447 276 715 932 184 329 532 795 520 707 941 662 365 767 697
 931 577 654 

### `Q-8:` You are given an array. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [45]:
# code here
import numpy as np
arr = np.array([[845, 100, 518, 123, 447, 276, 715, 932, 184, 329, 532, 795, 520, 707, 941, 662, 365, 767, 697, 931, 577, 654, 920, 501, 247, 588, 236, 469, 768, 785, 836, 848, 122, 310, 463, 654, 799, 312, 855, 675, 940, 349, 102, 216, 527, 671, 699, 110, 421, 830, 497, 733, 191, 143, 273, 516, 893, 319, 429, 846, 196, 479, 793, 524, 924, 569, 703, 753, 418, 800, 409, 947, 876, 405, 833, 288, 874, 621, 488, 518, 586, 118, 807, 461, 171, 775, 911, 551, 917, 240, 598, 638, 969, 865, 148, 805, 718, 602, 462, 775, 457, 239, 325, 929, 492, 790, 403, 806, 267, 474, 361, 972, 916, 209, 849, 992, 773, 615, 412, 289, 254, 585, 489, 778, 971, 657, 667, 559, 693, 344, 505, 183, 290, 349, 969, 295, 297, 500, 736, 208, 290, 141, 229, 726, 143, 149, 855, 424, 377, 994, 646, 849, 588, 338, 325, 678, 119, 754, 251, 714, 487, 335, 285, 175, 322, 882, 917, 778, 124, 370, 196, 721, 676, 882, 331, 828, 577, 879, 409, 711, 660, 796, 340, 640, 491, 899, 291, 145, 560, 255, 467, 820, 368, 190, 925, 475, 473, 340, 558, 846]])
arr.clip(min=100,max=700)
print(" \n",arr)

arr.sort()
print("sorted array: \n",arr)

cumsum = np.cumsum(arr)
print("Cumulative sum: \n",cumsum)

 
 [[845 100 518 123 447 276 715 932 184 329 532 795 520 707 941 662 365 767
  697 931 577 654 920 501 247 588 236 469 768 785 836 848 122 310 463 654
  799 312 855 675 940 349 102 216 527 671 699 110 421 830 497 733 191 143
  273 516 893 319 429 846 196 479 793 524 924 569 703 753 418 800 409 947
  876 405 833 288 874 621 488 518 586 118 807 461 171 775 911 551 917 240
  598 638 969 865 148 805 718 602 462 775 457 239 325 929 492 790 403 806
  267 474 361 972 916 209 849 992 773 615 412 289 254 585 489 778 971 657
  667 559 693 344 505 183 290 349 969 295 297 500 736 208 290 141 229 726
  143 149 855 424 377 994 646 849 588 338 325 678 119 754 251 714 487 335
  285 175 322 882 917 778 124 370 196 721 676 882 331 828 577 879 409 711
  660 796 340 640 491 899 291 145 560 255 467 820 368 190 925 475 473 340
  558 846]]
sorted array: 
 [[100 102 110 118 119 122 123 124 141 143 143 145 148 149 171 175 183 184
  190 191 196 196 208 209 216 229 236 239 240 247 251 254 255 267 273 276
  285 2

### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [54]:
# code here
arr = np.random.random(100)
print(arr)
rounded_arr = np.round(arr,decimals=3)
print("rounded arr: \n",rounded_arr)

zero_th_percentile = np.percentile(rounded_arr,0)
hundred_th_percentile = np.percentile(rounded_arr,100)
print("zero_th_percentile",zero_th_percentile)
print("hundred_th_percentile",hundred_th_percentile)

print("is min == 0th percentile: ",rounded_arr.min()==zero_th_percentile)
print("is max == 100th percentile: ",rounded_arr.max()==hundred_th_percentile)


[0.39115915 0.88118328 0.67847895 0.97033157 0.73724504 0.86428943
 0.25404889 0.44257565 0.76036754 0.71087661 0.22160348 0.99237992
 0.9755303  0.80638124 0.38916663 0.31166739 0.26595402 0.93360293
 0.7639064  0.27663153 0.00802686 0.61914248 0.90082086 0.44439265
 0.56678508 0.51184154 0.01472825 0.95888264 0.13135054 0.54908595
 0.02855053 0.7002624  0.3033558  0.12481347 0.22246927 0.80153504
 0.49708658 0.27041357 0.34006164 0.41919826 0.63238787 0.66584213
 0.42516813 0.38414362 0.09907858 0.81299734 0.30945175 0.81717166
 0.9732641  0.96549645 0.03517228 0.39810053 0.53283092 0.56103115
 0.36046933 0.6540776  0.47632144 0.69383678 0.12499812 0.94989899
 0.72870947 0.56768595 0.04203889 0.54129021 0.58672087 0.4405641
 0.21754505 0.09577009 0.06070833 0.54758498 0.08990703 0.6092243
 0.78761754 0.47275451 0.30536227 0.95813233 0.51045535 0.23393363
 0.09211877 0.34453561 0.40756026 0.88566118 0.44156315 0.89482743
 0.86716218 0.87137941 0.19385629 0.90540591 0.08317491 0.455699