<a href="https://colab.research.google.com/github/RealRohitDudi/Data_Science_Notes/blob/main/Task_13_NumPy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [ ]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [ ]:
#Code here
vector = np.zeros(10, dtype='int')
vector[4] = 1
print(vector)

[0 0 0 0 1 0 0 0 0 0]


###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [ ]:
#Code here
def generateRandom():
  a = int(input("Enter a: "))
  b = int(input("Enter b: "))
  array = np.random.random(a*b)
  print(array)
  print("average is: ", np.mean(array))

generateRandom()

Enter a: 3
Enter b: 4
[0.18609558 0.95260134 0.44585954 0.13376257 0.42180146 0.82702596
 0.28758027 0.36299298 0.76485512 0.4974821  0.06492414 0.35962271]
average is:  0.4420503145948193


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [ ]:
#Code here
def create_array():
  array = np.ones([4,4],dtype='int')
  array[1:3,1:3] = 0
  print(array)

create_array()

[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [ ]:
#Code here
vector = np.linspace(0,1,12)
print(vector)

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.        ]


###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [ ]:
#Code here
idmatrix = np.eye(3,4)
print(idmatrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [ ]:
#Code here
matrix = np.zeros((5,5))
matrix += np.arange(5)
print(matrix)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [ ]:
#code here
coordinates = np.random.randint(1, 101, size=(10, 2)) # Generate random integer coordinates (10,2)
point = np.array([2,3])

dx = coordinates[:, 0] - point[0]
dy = coordinates[:, 1] - point[1]

distance = np.sqrt(dx**2 + dy**2)

distance = distance.astype(int)

print(distance)

[ 68  58  31  75  67 117  45  57  61  82]


###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
#Code here
array = np.random.randint(1,100, size=(6,7,8))
# print(array)
count  = 0
for i in array.ravel():
  count +=
  if count == 100:
    print(np.where(array==i))

(array([1, 1, 2, 4]), array([3, 5, 2, 4]), array([3, 3, 4, 2]))


### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [ ]:
#Code here
numbers = "1 2 3 4 -8 -10"
array = np.array(numbers.split(" "), dtype='float')
print(numbers[::-1])

01- 8- 4 3 2 1


### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [ ]:
#Code here
array = np.random.randint(1,100, size=(3,4))
print(array)
print("total elements in this array are: ", np.size(array))

[[ 8  7 40 74]
 [96 51 23 97]
 [58 73 98  2]]
total elements in this array are:  12


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [ ]:
#Code here
def softmax(arr):
  if isinstance(arr, np.ndarray) and arr.ndim == 1:
    e = np.exp(arr - np.max(arr))
    return e / np.sum(e)
  else:
    raise ValueError("The input must be a 1D numpy array")

exp = np.array([33.17344305, 45.61961654, 82.05405781, 80.9647098,  68.82830233, 91.52064278])
print(softmax(exp))

[4.57181033e-26 1.16249922e-20 7.73872594e-05 2.60358426e-05
 1.39571531e-10 9.99896577e-01]


### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [ ]:
#Coder here
import numpy as np
array1 = np.random.randint(1,100,size=(4))
array2 = np.random.randint(1,100,size=(4))
print(array1)
print(array2)

joint = np.hstack((array1,array2),)
print("Joint: ",joint)

[82 14 41 50]
[85 60 82 95]
Joint:  [82 14 41 50 85 60 82 95]


### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [ ]:
#Code here
def dates_array(start,end):
  start_date = np.datetime64(start)
  end_date = np.datetime64(end)
  print(start_date)
  print(end_date)
  dates = np.arange(start_date, end_date)
  return dates

print(dates_array(start = '2020-11-25',end = '2020-11-30'))


2020-11-25
2020-11-30
['2020-11-25' '2020-11-26' '2020-11-27' '2020-11-28' '2020-11-29']


###`Q-14:` Subtract the mean of each row from a matrix.

In [ ]:
#code here
matrix = np.random.randint(1,100,size = (3,4))

for i in range(matrix.shape[0]):
  mean = np.mean(matrix[i])
  print(mean)
means = np.mean(matrix, axis=1)
print(matrix)
print(means)

40.75
49.0
49.25
[[41 17 72 33]
 [35 12 89 60]
 [ 2 91 30 74]]
[40.75 49.   49.25]


###`Q-15:` Swap column-1 of array with column-2 in the array.

In [52]:
#Code here
import numpy as np
array = np.random.randint(1,100,size = (3,4))
print(array)
column1 = array[:,1]
array[:,1] = array[:,2]
array[:,2] = column1

print(array)

[[94 48 30 29]
 [15 95 75 78]
 [61 11 58 56]]
[[94 30 30 29]
 [15 75 75 78]
 [61 58 58 56]]


###`Q-16:` Replace odd elements in arrays with -1.

In [57]:
#Code here
array = np.random.randint(1,100,size = (10))
print(array)
for i in range(len(array)):
  if array[i]%2 != 0:
    array[i] = -1
print(array)

[20 84 89 45 26 52 74  6 98 88]
[20 84 -1 -1 26 52 74  6 98 88]


###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [58]:
#Code here
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
result = np.maximum(a,b)
print(result)

[6 3 1 7 8]


###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [59]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[ 259, 4192, 1381, 9778, 9193],
       [1561, 4713, 6579, 2520,  217],
       [8571, 8714, 7723, 7551, 8028],
       [1187, 3861, 5098, 2015, 4892],
       [3797, 4721, 2748, 8587, 7321],
       [7749, 6850, 2683, 1933, 2078],
       [7796, 9943,  595, 9691, 7219],
       [3947, 2341, 3790, 8594, 8268]])

In [61]:
#Code here
import numpy as np
array  = np.random.randint(low=1,high=10000,size=40).reshape(8,5)

print(array)

alt_cols = array[:,::2]
normalized = (array - np.min(array))/np.max(array)- np.min(array)

print("alternate columns: ",alt_cols)
print("Normalized: ",normalized)

[[4517 2076 9753 2282 6563]
 [ 988 4930 9676 1869 9411]
 [5962 9673 4335  494 3336]
 [9830 8668 2948 8562 6142]
 [3811 9552  113 4993 3807]
 [8003 9094 7183 6325 3740]
 [9443 2356 1544 1472 1493]
 [4884 5985 7721  629 1426]]
alternate columns:  [[4517 9753 6563]
 [ 988 9676 9411]
 [5962 4335 3336]
 [9830 2948 6142]
 [3811  113 3807]
 [8003 7183 3740]
 [9443 1544 1493]
 [4884 7721 1426]]
Normalized:  [[-112.55198372 -112.80030519 -112.01932859 -112.77934893 -112.34384537]
 [-112.91098678 -112.50996948 -112.02716175 -112.82136317 -112.05412004]
 [-112.40498474 -112.02746694 -112.57049847 -112.9612411  -112.67212614]
 [-112.01149542 -112.12970498 -112.71159715 -112.1404883  -112.38667345]
 [-112.62380468 -112.0397762  -113.         -112.50356053 -112.6242116 ]
 [-112.19735504 -112.08636826 -112.28077314 -112.36805697 -112.63102747]
 [-112.0508647  -112.77182096 -112.85442523 -112.86174975 -112.85961343]
 [-112.51464903 -112.40264496 -112.22604273 -112.94750763 -112.8664293 ]]


###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [68]:
#Code here
def largest(arr,n):
  if n <= len(arr):
    sorted_arr = np.sort(arr)
    return sorted_arr[-n]

array = np.random.randint(1,100,size = (10))
print(array)
print(largest(array,2))

[62 59 88 90 40 55 21 56 58 70]
88


###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [80]:
#code here
a = np.array([1,2,3])
print(a)
pattern = np.hstack((np.repeat(a,3),a,a,a)) # each element of a is repeated 3 times and a+a+a stacked.
print(pattern)

[1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
